title: <p align="center"> Vansh Aggarwal </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vanshagg/">LinkedIn</a> |
  <a href="https://github.com/Vanshh003">GitHub</a>
  
  <br>   
intro
  <br>
  </p>



theme: jekyll-theme-minimal
